CREATE TABLE game (
                      id BIGINT AUTO_INCREMENT PRIMARY KEY,
                      title VARCHAR(100) NOT NULL,
                      description VARCHAR(500),
                      status VARCHAR(16) NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED')),
                      created_by BIGINT NOT NULL,
                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index on ('created_by')
CREATE INDEX idx_game_created_by ON game (created_by);

-- User
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);


CREATE TABLE player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    score INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_player_game FOREIGN KEY (game_id) REFERENCES game(id)
);

CREATE INDEX index_player_game_id ON player(game_id);
